### ISSUE TITLE
Need new 2.2 tag to fix renamed check() to audit()

### ISSUE THREAD

**Issue by briantully** [fiasco/drutiny-plugin-drupal-8#19]
Currently v2.1 has the Audit/ConfigCheck.php change where the the check() method was renamed to audit(). However within the remediate() method there is still a reference to $this->check() which causes the following error:

`Fatal error: Uncaught Error: Call to undefined method Drutiny\Plugin\Drupal8\Audit\ConfigCheck::check() in /Users/brian.tully/Sites/drutiny-cs-adaptor/vendor/drutiny/plugin-drupal-8/src/Audit/ConfigCheck.php:64
`

Please tag a new v2.2 which includes the fixes at https://github.com/drutiny/plugin-drupal-8/commit/58ba0522b3ccae4f9b81b4946cc7fc4d944c9860

We also should probably update drutiny-cs-adaptor's composer.json to require v2.2 of plugin-drupal-8 (once it's been tagged)

**Comment by fiasco** [comment]
done!

**Comment by briantully** [comment]
@fiasco  Do we also need a new package up on packagist.org?

**Comment by fiasco** [comment]
Its suppose to be automagic but it seems the webhooks don't always work. Thanks for checking, I've manually updated it on packagist.
