### ISSUE TITLE
drush 9 Fatal error

### ISSUE THREAD

**Issue by bigscotia10** [fiasco/drutiny-plugin-drupal-8#9]
Looks like I'm getting the following when running "/vendor/bin/drutiny profile:run d8_health_analysis" for a site using Drush 9.

Fatal error: Uncaught Error: Unsupported operand types in /Users/chris.ferrell/Sites/drutiny-cs-adaptor/vendor/drutiny/plugin-drupal-8/src/Audit/CronLast.php:30
Stack trace:
#0 /Users/chris.ferrell/Sites/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Audit.php(71): Drutiny\Plugin\Drupal8\Audit\CronLast->audit(Object(Drutiny\Sandbox\Sandbox))
#1 /Users/chris.ferrell/Sites/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Sandbox/Sandbox.php(78): Drutiny\Audit->execute(Object(Drutiny\Sandbox\Sandbox))
#2 /Users/chris.ferrell/Sites/drutiny-cs-adaptor/vendor/drutiny/drutiny/src/Command/ProfileRunCommand.php(194): Drutiny\Sandbox\Sandbox->run()
#3 /Users/chris.ferrell/Sites/drutiny-cs-adaptor/vendor/symfony/console/Command/Command.php(251): Drutiny\Command\ProfileRunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/chris.ferrell/Sites/drutiny-cs-adaptor/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Objec in /Users/chris.ferrell/Sites/drutiny-cs-adaptor/vendor/drutiny/plugin-drupal-8/src/Audit/CronLast.php on line 30

**Comment by fiasco** [comment]
Line 30 of `src/Audit/CronLast.php` is:

```php
$time_diff = time() - $last;
```

But I can't see how that would cause a `Unsupported operand types` error.

**Comment by fiasco** [comment]
Bit of concept of how `Unsupported operand types` would show up.

```
php > $last = ['asd'];
php > time() - $last;
PHP Warning:  Uncaught Error: Unsupported operand types in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
```

**Comment by ba66e77** [comment]
Yeah, using the --format=json option $last was an array. Using `$last['system.cron_last']` got it working.

```
$ drush @eebsmith.dev state-get 'system.cron_last' --format=json
{
    "system.cron_last": 1533810683
}
```

**Comment by fiasco** [comment]
Drutiny 2.3.x now has a Drush 9 driver which handles this output format.
